[package]
name = "tools"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
description = "build tools used by this project"

[[bin]]
name = "pkgconfig"
path = "src/pkgconfig.rs"
